from dataclasses import dataclass
from math import gcd, isqrt


@dataclass(frozen=True)
class RhoState:
    value: int
    a: int
    b: int


def ceil_sqrt(n: int) -> int:
    if n < 0:
        raise ValueError("n must be non-negative")

    root = isqrt(n)
    return root if root * root == n else root + 1


def mod_inverse(a: int, modulus: int) -> int:
    a %= modulus
    if modulus <= 1:
        raise ValueError("modulus must be greater than 1")

    old_r, r = a, modulus
    old_s, s = 1, 0
    while r:
        quotient = old_r // r
        old_r, r = r, old_r - quotient * r
        old_s, s = s, old_s - quotient * s

    if old_r != 1:
        raise ValueError("inverse does not exist")
    return old_s % modulus


def solve_linear_congruence(multiplier: int, rhs: int, modulus: int) -> list[int]:
    if modulus <= 0:
        raise ValueError("modulus must be positive")

    multiplier %= modulus
    rhs %= modulus
    shared = gcd(multiplier, modulus)
    if rhs % shared != 0:
        raise ValueError("collision cannot be solved")

    reduced_multiplier = multiplier // shared
    reduced_rhs = rhs // shared
    reduced_modulus = modulus // shared
    if reduced_modulus == 1:
        return list(range(shared))

    base = (
        reduced_rhs * mod_inverse(reduced_multiplier, reduced_modulus)
    ) % reduced_modulus
    return sorted((base + k * reduced_modulus) % modulus for k in range(shared))


def validate_dlp_instance(p: int, g: int, h: int, order: int) -> None:
    if p <= 2:
        raise ValueError("p must be greater than 2")
    if order <= 0:
        raise ValueError("order must be positive")
    if not 1 < g < p:
        raise ValueError("g must be in the multiplicative group")
    if not 0 < h < p:
        raise ValueError("h must be in the multiplicative group")
    if pow(g, order, p) != 1:
        raise ValueError("g does not have the claimed order")
    if pow(h, order, p) != 1:
        raise ValueError("target is not in the subgroup generated by g")


def baby_step_table(p: int, g: int, order: int) -> dict[int, int]:
    if order <= 0:
        raise ValueError("order must be positive")

    width = ceil_sqrt(order)
    table = {}
    value = 1
    for exponent in range(width):
        table.setdefault(value, exponent)
        value = (value * g) % p
    return table


def baby_step_giant_step(p: int, g: int, h: int, order: int) -> int:
    validate_dlp_instance(p, g, h, order)

    width = ceil_sqrt(order)
    table = baby_step_table(p, g, order)
    giant_stride = mod_inverse(pow(g, width, p), p)
    value = h % p

    for giant in range(width + 1):
        baby = table.get(value)
        if baby is not None:
            candidate = giant * width + baby
            if candidate < order and pow(g, candidate, p) == h % p:
                return candidate
        value = (value * giant_stride) % p

    raise ValueError("discrete log not found")


def rho_step(
    state: RhoState, p: int, g: int, h: int, order: int, salt: int = 0
) -> RhoState:
    bucket = (state.value + salt) % 3
    if bucket == 0:
        return RhoState((state.value * g) % p, (state.a + 1) % order, state.b)
    if bucket == 1:
        return RhoState((state.value * h) % p, state.a, (state.b + 1) % order)
    return RhoState(
        (state.value * state.value) % p,
        (2 * state.a) % order,
        (2 * state.b) % order,
    )


def recover_from_collision(
    p: int, g: int, h: int, order: int, left: RhoState, right: RhoState
) -> int:
    multiplier = (left.b - right.b) % order
    rhs = (right.a - left.a) % order
    for candidate in solve_linear_congruence(multiplier, rhs, order):
        if pow(g, candidate, p) == h % p:
            return candidate
    raise ValueError("collision did not yield a valid discrete log")


def pollard_rho_dlp(
    p: int,
    g: int,
    h: int,
    order: int,
    max_steps: int = 10_000,
    retries: int = 16,
) -> tuple[int, int]:
    validate_dlp_instance(p, g, h, order)
    if max_steps <= 0:
        raise ValueError("max_steps must be positive")
    if retries <= 0:
        raise ValueError("retries must be positive")
    if h % p == 1:
        return 0, 0

    for salt in range(retries):
        tortoise = RhoState(1, 0, 0)
        hare = RhoState(1, 0, 0)

        for step in range(1, max_steps + 1):
            tortoise = rho_step(tortoise, p, g, h, order, salt)
            hare = rho_step(
                rho_step(hare, p, g, h, order, salt), p, g, h, order, salt
            )

            if tortoise.value == hare.value:
                try:
                    return recover_from_collision(p, g, h, order, tortoise, hare), step
                except ValueError:
                    break

    raise ValueError("pollard rho failed; retry with a different walk")


def discrete_log(p: int, g: int, h: int, order: int, method: str = "bsgs") -> int:
    if method == "bsgs":
        return baby_step_giant_step(p, g, h, order)
    if method == "rho":
        result, _ = pollard_rho_dlp(p, g, h, order)
        return result
    raise ValueError("unknown method")


def main() -> None:
    p = 1019
    order = 509
    g = 4

    for secret in [37, 123, 400]:
        h = pow(g, secret, p)
        print(f"log_{g}({h}) mod {p} = {baby_step_giant_step(p, g, h, order)}")

    h = pow(g, 123, p)
    result, steps = pollard_rho_dlp(p, g, h, order)
    print(f"rho recovered {result} in {steps} Floyd steps")


if __name__ == "__main__":
    main()
