"""Schnorr identification protocol (toy, from scratch).

Run:
  python3 code/main.py

This lesson builds the Schnorr ID protocol (a Σ-protocol for discrete log)
as an *authentication* flow:
  1) Prover commits t = g^r
  2) Verifier sends random challenge c
  3) Prover responds s = r + c*x (mod q)
  4) Verifier checks g^s == t * y^c (mod p)

It also demonstrates the catastrophic "nonce reuse" failure mode: if the same
commitment t is used for two different challenges, the secret x can be
recovered.

Educational implementation. Not constant-time. Not production-safe.
"""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
from pathlib import Path
import random
import secrets


def egcd(a: int, b: int) -> tuple[int, int, int]:
    """Extended GCD: returns (g, x, y) such that a*x + b*y = g = gcd(a, b)."""
    if b == 0:
        return (abs(a), 1 if a >= 0 else -1, 0)
    g, x1, y1 = egcd(b, a % b)
    return (g, y1, x1 - (a // b) * y1)


def mod_inv(a: int, mod: int) -> int:
    """Multiplicative inverse of a modulo mod. Raises ValueError if none."""
    a = a % mod
    if a == 0:
        raise ValueError("0 has no inverse modulo mod")
    g, x, _y = egcd(a, mod)
    if g != 1:
        raise ValueError("a and mod are not coprime")
    return x % mod


def mod_mul(a: int, b: int, mod: int) -> int:
    return (a % mod) * (b % mod) % mod


def mod_pow(base: int, exp: int, mod: int) -> int:
    return pow(base % mod, exp, mod)


def hash_to_int_sha256(data: bytes, mod: int) -> int:
    """Hash bytes to an integer in [0, mod)."""
    if mod <= 0:
        raise ValueError("mod must be positive")
    digest = hashlib.sha256(data).digest()
    return int.from_bytes(digest, "big") % mod


@dataclass(frozen=True)
class SchnorrParams:
    """Toy subgroup parameters for Schnorr-style proofs.

    We work in the subgroup of Z_p* generated by g with prime order q.
    """

    p: int
    q: int
    g: int


def schnorr_params_toy() -> SchnorrParams:
    """Small, non-secure parameters for a readable demo."""
    return SchnorrParams(p=23, q=11, g=2)


def assert_schnorr_params(params: SchnorrParams, y: int) -> None:
    if params.p <= 2 or params.q <= 1:
        raise ValueError("bad group parameters")
    if (params.p - 1) % params.q != 0:
        raise ValueError("q must divide p-1")
    if not (1 < params.g < params.p):
        raise ValueError("g must satisfy 1 < g < p")
    if mod_pow(params.g, params.q, params.p) != 1:
        raise ValueError("g does not have order q")
    if mod_pow(y, params.q, params.p) != 1:
        raise ValueError("y is not in the subgroup of order q")


def rand_zq(q: int, rng: random.Random | None = None) -> int:
    """Sample uniformly from Z_q.

    If rng is provided, uses deterministic sampling for tests/vectors.
    """
    if q <= 1:
        raise ValueError("q must be > 1")
    if rng is None:
        return secrets.randbelow(q)
    return rng.randrange(q)


def schnorr_public_key(params: SchnorrParams, x: int) -> int:
    x = x % params.q
    return mod_pow(params.g, x, params.p)


def schnorr_id_commit(params: SchnorrParams, r: int) -> int:
    """Commitment t = g^r (mod p)."""
    r = r % params.q
    return mod_pow(params.g, r, params.p)


def schnorr_id_respond(q: int, r: int, c: int, x: int) -> int:
    """Response s = r + c*x (mod q)."""
    return (r + (c % q) * (x % q)) % q


def schnorr_id_verify(params: SchnorrParams, y: int, t: int, c: int, s: int) -> bool:
    """Verifier check for Schnorr ID transcripts."""
    if not (0 <= c < params.q):
        return False
    if not (0 <= s < params.q):
        return False
    if not (0 <= t < params.p):
        return False
    left = mod_pow(params.g, s, params.p)
    right = mod_mul(t, mod_pow(y, c, params.p), params.p)
    return left == right


@dataclass(frozen=True)
class SchnorrIdTranscript:
    """An identification transcript: (commitment t, challenge c, response s)."""

    t: int
    c: int
    s: int


def schnorr_id_prove(params: SchnorrParams, x: int, r: int, c: int) -> SchnorrIdTranscript:
    """Compute a Schnorr ID transcript for fixed nonce r and challenge c."""
    t = schnorr_id_commit(params, r)
    s = schnorr_id_respond(params.q, r, c, x)
    return SchnorrIdTranscript(t=t, c=c % params.q, s=s)


def schnorr_id_simulate_hvz(
    params: SchnorrParams, y: int, c: int, s: int
) -> SchnorrIdTranscript:
    """Special HVZK simulator for Schnorr ID.

    Pick (c, s) and compute a commitment t that makes verification pass:
      g^s = t * y^c   =>   t = g^s * (y^c)^(-1)  (mod p)
    """
    c = c % params.q
    s = s % params.q
    y_to_c = mod_pow(y, c, params.p)
    t = mod_mul(mod_pow(params.g, s, params.p), mod_inv(y_to_c, params.p), params.p)
    return SchnorrIdTranscript(t=t, c=c, s=s)


def schnorr_extract_secret_from_nonce_reuse(q: int, c1: int, s1: int, c2: int, s2: int) -> int:
    """Recover x from two accepting transcripts with the same commitment and c1 != c2."""
    c1 = c1 % q
    c2 = c2 % q
    s1 = s1 % q
    s2 = s2 % q
    if c1 == c2:
        raise ValueError("need two different challenges to extract")
    num = (s1 - s2) % q
    den = (c1 - c2) % q
    return (num * mod_inv(den, q)) % q


def schnorr_fiat_shamir_challenge(
    q: int, *, domain_sep: str, statement_y: int, commitment_t: int
) -> int:
    """Compute a Fiat–Shamir style challenge c = H(context) mod q."""
    if q <= 1:
        raise ValueError("q must be > 1")
    if domain_sep == "":
        raise ValueError("domain_sep must be non-empty")
    msg = f"{domain_sep}|y={statement_y}|t={commitment_t}".encode("utf-8")
    return hash_to_int_sha256(msg, q)


def load_vectors_file(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def fmt_transcript(tr: SchnorrIdTranscript) -> str:
    return f"(t={tr.t}, c={tr.c}, s={tr.s})"


def step_1_group_and_statement(params: SchnorrParams) -> tuple[int, int]:
    print("=== Step 1: Parameters, secret, and public statement ===")
    x = 3
    y = schnorr_public_key(params, x)
    assert_schnorr_params(params, y)
    print(f"params: p={params.p}, q={params.q}, g={params.g}")
    print(f"secret x = {x}")
    print(f"public statement y = g^x mod p = {y}")
    return (x, y)


def step_2_interactive_id(params: SchnorrParams, x: int, y: int) -> SchnorrIdTranscript:
    print("=== Step 2: Interactive Schnorr ID (commit → challenge → response) ===")
    r = 4
    t = schnorr_id_commit(params, r)
    c = 5
    s = schnorr_id_respond(params.q, r, c, x)
    ok = schnorr_id_verify(params, y, t, c, s)
    tr = SchnorrIdTranscript(t=t, c=c, s=s)
    print(f"commit: t = g^r mod p = {t} (r={r})")
    print(f"challenge: c = {c}")
    print(f"response: s = r + c*x mod q = {s}")
    print(f"transcript: {fmt_transcript(tr)}")
    print(f"verifier accepts: {ok}")
    return tr


def step_3_hvz_simulation(params: SchnorrParams, y: int) -> SchnorrIdTranscript:
    print("=== Step 3: HVZK simulation (no secret needed) ===")
    c = 2
    s = 7
    tr = schnorr_id_simulate_hvz(params, y, c, s)
    ok = schnorr_id_verify(params, y, tr.t, tr.c, tr.s)
    print(f"simulated transcript: {fmt_transcript(tr)}")
    print(f"verifier accepts: {ok}")
    return tr


def step_4_nonce_reuse_attack(params: SchnorrParams, x: int, y: int) -> None:
    print("=== Step 4: Nonce reuse breaks the secret (extract x) ===")
    r = 4
    t = schnorr_id_commit(params, r)
    c1, c2 = 2, 5
    s1 = schnorr_id_respond(params.q, r, c1, x)
    s2 = schnorr_id_respond(params.q, r, c2, x)
    ok1 = schnorr_id_verify(params, y, t, c1, s1)
    ok2 = schnorr_id_verify(params, y, t, c2, s2)
    extracted = schnorr_extract_secret_from_nonce_reuse(params.q, c1, s1, c2, s2)

    print(f"same commitment t = {t} (same r)")
    print(f"t1 = (t={t}, c={c1}, s={s1}) -> accepts={ok1}")
    print(f"t2 = (t={t}, c={c2}, s={s2}) -> accepts={ok2}")
    print(f"extract(c1,s1,c2,s2) -> x = {extracted} (matches: {extracted == (x % params.q)})")


def step_5_fiat_shamir_preview(params: SchnorrParams, x: int, y: int) -> None:
    print("=== Step 5: Fiat–Shamir preview (binding transcript to context) ===")
    r = 6
    t = schnorr_id_commit(params, r)
    c = schnorr_fiat_shamir_challenge(
        params.q, domain_sep="schnorr-id-demo-v1", statement_y=y, commitment_t=t
    )
    s = schnorr_id_respond(params.q, r, c, x)
    ok = schnorr_id_verify(params, y, t, c, s)
    print(f"commitment t = {t} (r={r})")
    print(f"challenge c = H(domain||y||t) mod q = {c}")
    print(f"response s = {s}")
    print(f"verifier accepts: {ok}")


def main() -> None:
    params = schnorr_params_toy()

    x, y = step_1_group_and_statement(params)
    _interactive = step_2_interactive_id(params, x, y)
    _simulated = step_3_hvz_simulation(params, y)
    step_4_nonce_reuse_attack(params, x, y)
    step_5_fiat_shamir_preview(params, x, y)


if __name__ == "__main__":
    main()
