"""Sigma protocols from scratch (toy Schnorr discrete-log instance).

Run:
  python3 code/main.py

This lesson builds a tiny Σ-protocol and demonstrates the three properties
you will use throughout zero-knowledge:
  - Completeness: honest prover convinces honest verifier.
  - Special HVZK: a simulator can generate accepting transcripts without the witness.
  - Special soundness: two accepting transcripts with the same commitment but
    different challenges let you extract the witness.

Educational implementation. Not constant-time. Not production-safe.
"""

from __future__ import annotations

from dataclasses import dataclass


def egcd(a: int, b: int) -> tuple[int, int, int]:
    """Extended GCD: returns (g, x, y) such that a*x + b*y = g = gcd(a, b)."""
    if b == 0:
        return (abs(a), 1 if a >= 0 else -1, 0)
    g, x1, y1 = egcd(b, a % b)
    return (g, y1, x1 - (a // b) * y1)


def mod_inv(a: int, mod: int) -> int:
    """Multiplicative inverse of a modulo mod. Raises ValueError if none."""
    a = a % mod
    if a == 0:
        raise ValueError("0 has no inverse modulo mod")
    g, x, _y = egcd(a, mod)
    if g != 1:
        raise ValueError("a and mod are not coprime")
    return x % mod


def mod_mul(a: int, b: int, mod: int) -> int:
    return (a % mod) * (b % mod) % mod


def mod_pow(base: int, exp: int, mod: int) -> int:
    return pow(base % mod, exp, mod)


@dataclass(frozen=True)
class SigmaTranscript:
    """A Σ-protocol transcript: (commitment, challenge, response)."""

    commitment: int
    challenge: int
    response: int


@dataclass(frozen=True)
class SchnorrParams:
    """Toy subgroup parameters for Schnorr-style proofs.

    We work in the subgroup of Z_p* generated by g with prime order q.
    """

    p: int
    q: int
    g: int


def assert_schnorr_params(params: SchnorrParams, y: int) -> None:
    if params.p <= 2 or params.q <= 1:
        raise ValueError("bad group parameters")
    if (params.p - 1) % params.q != 0:
        raise ValueError("q must divide p-1")
    if not (1 < params.g < params.p):
        raise ValueError("g must satisfy 1 < g < p")
    if mod_pow(params.g, params.q, params.p) != 1:
        raise ValueError("g does not have order q")
    if mod_pow(y, params.q, params.p) != 1:
        raise ValueError("y is not in the subgroup of order q")


def schnorr_public_key(params: SchnorrParams, x: int) -> int:
    x = x % params.q
    return mod_pow(params.g, x, params.p)


def schnorr_commit(params: SchnorrParams, r: int) -> int:
    r = r % params.q
    return mod_pow(params.g, r, params.p)


def schnorr_response(q: int, r: int, c: int, x: int) -> int:
    return (r + c * x) % q


def schnorr_verify(params: SchnorrParams, y: int, a: int, c: int, s: int) -> bool:
    if not (0 <= c < params.q):
        return False
    if not (0 <= s < params.q):
        return False
    if not (0 <= a < params.p):
        return False
    left = mod_pow(params.g, s, params.p)
    right = mod_mul(a, mod_pow(y, c, params.p), params.p)
    return left == right


def schnorr_simulate_hvz(
    params: SchnorrParams, y: int, c: int, s: int
) -> SigmaTranscript:
    """Special HVZK simulator for Schnorr transcripts.

    Pick (c, s) and compute a so that verification passes:
      g^s = a * y^c   =>   a = g^s * (y^c)^(-1)  (mod p)
    """
    c = c % params.q
    s = s % params.q
    y_to_c = mod_pow(y, c, params.p)
    a = mod_mul(mod_pow(params.g, s, params.p), mod_inv(y_to_c, params.p), params.p)
    return SigmaTranscript(commitment=a, challenge=c, response=s)


def schnorr_extract_witness(q: int, c1: int, s1: int, c2: int, s2: int) -> int:
    """Extract x from two accepting transcripts with same commitment and c1 != c2."""
    if c1 == c2:
        raise ValueError("need two different challenges to extract")
    num = (s1 - s2) % q
    den = (c1 - c2) % q
    return (num * mod_inv(den, q)) % q


def schnorr_prove(
    params: SchnorrParams, x: int, r: int, c: int
) -> SigmaTranscript:
    a = schnorr_commit(params, r)
    s = schnorr_response(params.q, r, c, x)
    return SigmaTranscript(commitment=a, challenge=c % params.q, response=s)


def fmt_transcript(t: SigmaTranscript) -> str:
    return f"(a={t.commitment}, c={t.challenge}, s={t.response})"


def step_1_shape() -> None:
    print("=== Step 1: The Σ transcript type ===")
    t = SigmaTranscript(commitment=16, challenge=5, response=8)
    print(f"transcript = {fmt_transcript(t)}")
    print("A Σ-protocol transcript is always: commitment a, challenge c, response s.")


def step_2_schnorr_core(params: SchnorrParams) -> tuple[int, int]:
    print("=== Step 2: Schnorr core operations ===")
    x = 3
    y = schnorr_public_key(params, x)
    assert_schnorr_params(params, y)
    print(f"params: p={params.p}, q={params.q}, g={params.g}")
    print(f"statement: y = g^x mod p = {y}")
    return (x, y)


def step_3_completeness(params: SchnorrParams, x: int, y: int) -> SigmaTranscript:
    print("=== Step 3: Prove and verify (completeness) ===")
    r = 4
    c = 5
    t = schnorr_prove(params, x, r, c)
    ok = schnorr_verify(params, y, t.commitment, t.challenge, t.response)
    print(f"witness x = {x}, nonce r = {r}, challenge c = {c}")
    print(f"transcript: {fmt_transcript(t)}")
    print(f"verifier accepts: {ok}")
    return t


def step_4_hvz_simulation(params: SchnorrParams, y: int) -> SigmaTranscript:
    print("=== Step 4: Special HVZK simulator (no witness) ===")
    c = 2
    s = 7
    t = schnorr_simulate_hvz(params, y, c, s)
    ok = schnorr_verify(params, y, t.commitment, t.challenge, t.response)
    print(f"simulated transcript: {fmt_transcript(t)}")
    print(f"verifier accepts: {ok}")
    return t


def step_5_special_soundness(params: SchnorrParams, x: int, y: int) -> None:
    print("=== Step 5: Special soundness extractor (two transcripts -> witness) ===")
    r = 4
    a = schnorr_commit(params, r)
    c1, c2 = 2, 5
    s1 = schnorr_response(params.q, r, c1, x)
    s2 = schnorr_response(params.q, r, c2, x)
    ok1 = schnorr_verify(params, y, a, c1, s1)
    ok2 = schnorr_verify(params, y, a, c2, s2)
    extracted = schnorr_extract_witness(params.q, c1, s1, c2, s2)

    print(f"same commitment a = {a} (same r)")
    print(f"t1 = (a={a}, c={c1}, s={s1}) -> accepts={ok1}")
    print(f"t2 = (a={a}, c={c2}, s={s2}) -> accepts={ok2}")
    print(f"extract(c1,s1,c2,s2) -> x = {extracted} (matches: {extracted == (x % params.q)})")


def main() -> None:
    params = SchnorrParams(p=23, q=11, g=2)

    step_1_shape()
    x, y = step_2_schnorr_core(params)
    _real = step_3_completeness(params, x, y)
    _sim = step_4_hvz_simulation(params, y)
    step_5_special_soundness(params, x, y)


if __name__ == "__main__":
    main()
